config/routes.rb
Rails.application.routes.draw do
  resources :authors
  root "authors#index"

  get "signup", to: "users#new"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  resources :users, except: [:new]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
    has_many(
    :publishers,
    class_name: 'Publisher',
    foreign_key: 'authors_id',
    inverse_of: :publisher,
    dependent: :destroy
  )
end

app/models/publisher.rb
class Publisher < ApplicationRecord
    belongs_to(
        :publisher,
        class_name: 'Author',
        foreign_key: 'authors_id',
        inverse_of: :publishers
      )
end

app/models/user.rb
class User < ApplicationRecord

        has_secure_password
      
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?
    def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    def logged_in?
    !!current_user
    end
    def require_user
    if !logged_in?
        flash[:alert] = "You must be logged in to perform that action."
        redirect_to login_path
    end
    end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author_params, only: %i[show edit update destroy]
  before_action :logged_in_user, only: [:edit, :update, :destroy]


  def index
    @authors = Author.all
  end

  def new
    @author = Author.new
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

  def create
    @author = Author.create(author_params)
    if @author.valid?
      flash[:errors] = 'Author Added Successfully'
      redirect_to authors_path
    else
      flash[:errors] = @author.errors.full_messages
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @author.update(author_params)
      flash[:errors] = 'Author Updated Successfully'
      redirect_to author_path(@author)
    else
      flash[:errors] = @author.errors.full_messages
      redirect_to edit_author_path
    end
  end

  def destroy
    if @author.delete
      flash[:errors] = 'Author Deleted Successfully'
      redirect_to root_path(@author)
    else
      flash[:errors] = @author.errors.full_messages
      redirect_to destroy_author_path
    end
  end

  private

  def set_author_params
    @author = Author.find(params[:id])
  end

  def author_params
    params.require(:author).permit(:author_name, :gender, { books: [] }, :age, :publisher, :number_of_books_published)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def create
        user = User.find_by(username: params[:session][:username].downcase)
        if user && user.authenticate(params[:session][:password])
          session[:user_id] = user.id
          flash[:errors] = "Logged in successfully."
          redirect_to root_path
        else
          flash[:errors] = "There is something wrong with your login details."
          render 'new'
        end
      end
      def destroy
        session[:user_id] = nil
        flash[:errors] = "You have been logged out."
        redirect_to root_path
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end
   
    def create
        @user = User.new(user_params)
        if @user.save
          flash[:errors] = "User created."
          redirect_to root_path
        else
          render 'new'
     end
    end
      private
      def user_params
        params.require(:user).permit(:username, :password)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/create.html.erb
<h1>Authors#create</h1>
<p>Find me in app/views/authors/create.html.erb</p>

app/views/authors/destroy.html.erb
<h1>Authors#destroy</h1>
<p>Find me in app/views/authors/destroy.html.erb</p>

app/views/authors/edit.html.erb
<div class="flex-column d-flex align-items-center justify-content-center" >
<h1>Edit Author</h1>
  <div class="card shadow" style="width: 60rem;">
    <div class="card-header color="#172044" ">
      <h2 class="text-center">Author Information</h2>
    </div>
    <div class="card-body">
      <% if flash[:errors] %>
        <% flash[:errors].each do |error| %>
          <p class="text-danger"><%= error %></p>
        <% end %>
      <% end %>
      <%= form_with model: @author do |f| %>
        <%= f.label :author_name, "Author Name :", class:"mt-3" %>
        <%= f.text_field :author_name ,placeholder: "Enter Author's Name",required: true,class:"mb-2 form-control" %>
        <br>
        <%= f.label :age, "Author Age :", class:"mt-3" %>
        <%= f.text_field :age ,placeholder: "Enter Author's Age",required: true,class:"mb-2 form-control" %>
        <br>
        <div class="form-group">
          <%= f.label "Gender :" %>
          <%= f.radio_button :gender, "male" %>
          <%= f.label :gender, "Male" %>
          <%= f.radio_button :gender, "female" %>
          <%= f.label :gender, "Female" %>
        </div>
        <br>
        <div class="form-group">
          <%= f.label "Genres :" %>
          <%= f.check_box :books, { multiple: true },"Romance", false %>
          <%= f.label :books, "Romance" %>
          <%= f.check_box :books, { multiple: true },"Thriller", false %>
          <%= f.label :books, "Thriller" %>
          <%= f.check_box :books, { multiple: true },"Self Help", false %>
          <%= f.label :books, "Self Help" %> 
        </div>
        <br>
        <%= f.label :publisher, "Name Of Publisher :", class:"mt-3" %>
        <%= f.text_field :publisher ,placeholder: "Enter Name Of The Publisher",required: true,class:"mb-2 form-control" %>
        <br>
        <%= f.label :number_of_books_published, "Total Number Of Books Published :", class:"mt-3" %>
        <%= f.text_field :number_of_books_published ,placeholder: "Enter Total Number Of Books Published",required: true,class:"mb-2 form-control" %>
        <br>
        <%= f.submit "Save Information", class:"btn-primary border-0 rounded-pill shadow p-3" %>
      <% end %>
    </div>
  </div>
</div>

app/views/authors/index.html.erb
<div class="flex-column  d-flex align-items-center justify-content-center .bg-light" style = "height: auto;">
  <h1> Published Authors List 2024</h1>
  <% if flash[:errors] %>
    <% flash.each do |name,message| %>
      <p class="text-danger"><%= message%></p>
    <% end %>
  <% end %>
  <!-- Author Table -->
  <div>
    <div class="btn-group">
      <%= button_to "Log In", login_path, method: :get, class:"bg-secondary border-0 rounded-pill shadow p-3 m-3" unless logged_in? %>
      <%= button_to "Log Out", logout_path, method: :delete, class:"bg-secondary border-0 rounded-pill shadow p-3 m-3" if logged_in?  %>
      <%= button_to "Sign Up", signup_path, method: :get, class:"bg-secondary border-0 rounded-pill shadow p-3 m-3" %>
    </div> 
   <table class="table table-light table-striped">
      <ol class="fs-2">
        <thead class="table-light">
          <td class="text-center"> Id </td>
          <td class="text-center"> Name </td>
          <td class="text-center"> Age </td>
          <td class="text-center"> Genres </td>
          <td class="text-center"> Publisher </td>
          <td class="text-center"> Total Number of Books Published</td>
          <td colspan=3 class="text-center"> Action </td>
        </thead>
        <% @authors.each do |a| %>
          <tr>
            <td class="text-center"> <%= a.id %> </td>
            <td class="text-center"> <%= link_to a.author_name, author_path(a) %> </td>
            <td class="text-center"> <%= a.age %> </td>
            <td class="text-center"> <%= a.books %> </td>
            <td class="text-center"> <%= a.publisher%> </td>
            <td class="text-center"> <%= a.number_of_books_published %> </td>
            <td class="text-center"><%= button_to "Show",author_path(a),method: :get, class:"bg-secondary border-0 rounded-pill shadow px-3 py-2" %></td>
            <td class="text-center"><%= button_to "Edit",edit_author_path(a),method: :get, class:"bg-secondary border-0 rounded-pill shadow px-3 py-2" %></td>
            <td class="text-center"><%= button_to "Delete",author_path(a),method: :delete, class:"btn-danger border-0 rounded-pill shadow px-3 py-2" %></td>
          </tr>
        <% end %>
      </ol>
    </table>
  </div>
  <div class="d-flex">
    <%= button_to "Add New Author", new_author_path, method: :get ,class:"bg-secondary border-0 rounded-pill shadow p-3 m-3" %>
  </div>
</div>

app/views/authors/new.html.erb
<div class="flex-column d-flex align-items-center justify-content-center">
  <div class="card shadow" style="width: 36rem;">
    <div class="card-header">
      <h2 class="text-center">Author Form</h2>
    </div>
    <div class="card-body">
      <% if flash[:errors] %>
        <% flash[:errors].each do |error| %>
          <p class="text-danger"><%= error %></p>
        <% end %>
      <% end %>
      <%= form_with model: @author do |f| %>
        <%= f.label :author_name, "Author Name :", class:"mt-3" %>
        <%= f.text_field :author_name ,placeholder: "Enter Author's Name",required: true,class:"mb-2 form-control" %>
        <br>
        <%= f.label :age, "Author Age :", class:"mt-3" %>
        <%= f.text_field :age ,placeholder: "Enter Author's Age",required: true,class:"mb-2 form-control" %>
        <div class="form-group">
          <%= f.label "Gender :" %>
          <%= f.radio_button :gender, "male" %>
          <%= f.label :gender, "Male" %>
          <%= f.radio_button :gender, "female" %>
          <%= f.label :gender, "Female" %>
        </div>
        <br>
        <div class="form-group">
          <%= f.label "Genres :" %>
          <%= f.check_box :books, { multiple: true },"Romance", false %>
          <%= f.label :books, "Romance" %>
          <%= f.check_box :books, { multiple: true },"Thriller", false %>
          <%= f.label :books, "Thriller" %>
          <%= f.check_box :books, { multiple: true },"Self Help", false %>
          <%= f.label :books, "Self Help" %>
        </div>
        <br>
        <%= f.label :publisher, "Name Of Publisher :", class:"mt-3" %>
        <%= f.text_field :publisher ,placeholder: "Enter Name Of The Publisher",required: true,class:"mb-2 form-control" %>
        <br>
        <%= f.label :number_of_books_published, "Total Number Of Books Published :", class:"mt-3" %>
        <%= f.text_field :number_of_books_published ,placeholder: "Enter Total Number Of Books Published",required: true,class:"mb-2 form-control" %>
        <%= f.submit "Save Author", class:"btn-primary border-0 rounded-pill shadow p-3" %>
      <% end %>
    </div>
  </div>
</div>

app/views/authors/show.html.erb
<div class="flex-column d-flex align-items-center justify-content-center" style="height:100vh;">
  <% if flash[:errors] %>
    <% flash.each do |name,message| %>
      <p class="text-danger"><%= message%></p>
    <% end %>
  <% end %>
  <div class="d-flex">
    <div class="m-5" >
      <div class="card bg-light border-secondary shadow">
        <div class="card-body">
          <div class="card-header">
            <h2 class="text-center">Author's Details</h2>
          </div>
          <div>
            <h3>  Author ID: <%= @author.id %> </h3>
            <h3>  Name: <%= @author.author_name %> </h3>
            <h3>  Age: <%= @author.age %> </h3>
            <h3>  Gender: <%= @author.gender %> </h3>
            <h3>  Genres: <%= @author.books %> </h3>
            <h3>  Publisher: <%= @author.publisher %> </h3>
            <h3>  Total Number Of Books Published: <%= @author.number_of_books_published %> </h3>
          </div>
          <div class="d-flex">
            <%= button_to "Edit Author" , edit_author_path, method: :get ,class:"bg-secondary border-0 rounded-pill shadow p-2 m-2" %>
            <%= button_to "View all Authors", authors_path,method: :get ,class:"bg-secondary border-0 rounded-pill shadow p-2 m-2" %>
            <%= button_to "Delete Author", author_path, method: :delete ,class:"btn-danger border-0 rounded-pill shadow p-2 m-2" %>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/authors/update.html.erb
<h1>Authors#update</h1>
<p>Find me in app/views/authors/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title>Author Information</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  </head>
  <!--Bootstrap CDN  -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<div class="flex-column d-flex align-items-center justify-content-center" >
<h1>Sign Up</h1>
<% if flash[:errors] %>
    <% flash.each do |name,message| %>
      <p class="text-danger"><%= message%></p>
    <% end %>
  <% end %>
<div class="card shadow" style="width: 60rem;">
<div class="card-header color="#172044" ">
      <h2 class="text-center">Sign Up</h2>
    </div>
  <div class="card-body">
  <%= form_with(model: @user, local: true) do |f| %>
      <div class="form-group">
        <%= f.label :username, class:"mt-3" %><br/>
        <%= f.text_field :username, class:"mb-2 form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :password, class:"mt-3" %><br/>
        <%= f.password_field :password, class:"mb-2 form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit class:"btn-primary border-0 rounded-pill shadow p-3" %>
      </div>
      <% end %>
  </div>
</div>
<%= button_to "Log In", login_path, method: :get, class:"bg-secondary border-0 rounded-pill shadow p-3 m-3" %>
</div>